name: Deploy Frontend

on: [workflow_dispatch]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies"
        run: npm ci
        working-directory: "./frontend"
      - name: "Build"
        run: npm run build
        working-directory: "./frontend"
      - name: "Pack the project into an archive"
        run: mkdir packedDist && tar -cf ./packedDist/frontend.tar -C ./dist .
        working-directory: "./frontend"
      - name: "Deploy built project on VPS"
        uses: wangyucode/sftp-upload-action@main
        with:
          host: "${{ secrets.SFTP_ADDRESS }}"
          port: "${{ secrets.SFTP_PORT }}"
          username: "${{ secrets.SFTP_USERNAME }}"
          password: "${{ secrets.SFTP_PASSWORD }}"
          localDir: "./frontend/packedDist"
          remoteDir: "/home/${{ secrets.SFTP_USERNAME }}/gh/"
          dryRun: false
      - name: "Run deploy script on server"
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: "bash deploy_www.sh"
          host: "${{ secrets.SFTP_ADDRESS }}"
          port: "${{ secrets.SFTP_PORT }}"
          username: "${{ secrets.SFTP_USERNAME }}"
          password: "${{ secrets.SFTP_PASSWORD }}"
